#!/bin/bash

case $- in
    *i*) ;;
    *) return 0 2>/dev/null || exit 0 ;;
esac

if [ ! "$(uname)" = 'Darwin' ]; then
    if [ -e "$HOME/.linuxbrew/bin/brew" ]; then
        eval "$("$HOME/.linuxbrew/bin/brew" shellenv)"
    elif [ -e /home/linuxbrew/.linuxbrew/bin/brew ]; then
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
    fi
fi

if command -v zsh 1>/dev/null 2>&1; then
    SHELL="$(command -v zsh)"
    export SHELL
    exec "$SHELL" -l
fi
