# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# .aliasesを読み込み
if [ -f $HOME/.aliases ]; then
  . $HOME/.aliases
fi

# 自作シェススクリプトの読み込み
if [ -f $HOME/.utils ]; then
  . $HOME/.utils
fi

# fpath
fpath+=~/.zfunc

# ghq + peco でgitリポジトリをインクリメントサーチ
function peco-src () {
  local selected_dir=$(ghq list -p | peco --query "$LBUFFER")
  if [ -n "$selected_dir" ]; then
    BUFFER="cd ${selected_dir}"
    zle accept-line
  fi
  zle clear-screen
}
zle -N peco-src
bindkey '^]' peco-src

#pyenvの設定
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"



# zsh 補間
autoload -U compinit
compinit
