format = """\
$shlvl\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$ruby\
$rust\
$swift\
$terraform\
$zig\
$nix_shell\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$username\
$hostname\
$cmd_duration\
$line_break\
$conda\
$custom\
$lua\
$jobs\
$battery\
$time\
$status\
$character\
"""

[character]
success_symbol = "[❯](bold fg:147)"
error_symbol = "[❯](bold red)"

[cmd_duration]
format = "[$duration](bold yellow) "

[directory]
truncation_length = 10
truncate_to_repo = false
format = "[$path](purple)[$read_only](purple) "

[git_branch]
format = "[$branch](fg:245)"

[git_status]
format = "[$all_status](red) "

[username]
format = "[$user@](fg:245)"

[hostname]
ssh_only = true
format = "[$hostname](fg:245) "

[python]
disabled = true

[conda]
format = "[$environment](fg:245) "
