shell = "zsh"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.compinit]
inline = "autoload -Uz compinit && compinit"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["zsh-autosuggestions.zsh"]

[plugins.pure]
github = "sindresorhus/pure"
use = ["async.zsh", "pure.zsh"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
use = ["zsh-syntax-highlighting.zsh"]
